apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato
  namespace: zomato-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: zomato
        image: psschiatanya/zomato:25_20250223_1026
        ports:
        - containerPort: 3000   # Use port 3000
