apiVersion: v1
kind: Service
metadata:
  name: zomato-service
  namespace: zomato-dev
spec:
  selector:
    app: zomato
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
